{  secrets, ... }:
{
  programs.git = {
    enable = true;
    userName = "Haf";
    userEmail = "haf@protonmail.ch";
    signing.key = "7E66BB1D1107BA57";
    ignores = [ 
      "*~"
      "*.swp" # vim swap files 
      "texfrag" # trash generated by texfrag in emacs
      "\\#*\\#" # emacs swap files
      "/result/" # nix outputs
      "/result-data/" # something related to nix output
      ".idea" # Jetbrains IDEA configuration
      "build" # gradle output
      ".gradle" # some gradle specifics I dunno
      "hs_err_pid*.log" # some Java crash logs
      "replay_pid*.log" # other random Java crash logs I guess
    ];
    extraConfig = {
      credential.helper = "cache --timeout=3600";
      init.defaultBranch = "main";
      merge = {
        # Always creates a merge commit, even if a merge can be fast-forwarded.
        # If the commits are fast-forwarded, these might be very bulk in the history
        # of the base branch and make it difficult to use debugging tools like bisect,
        # or force you to revert them all if you wan't to undo the merge.

        # On the other hand, if you have a merge commit, you can just revert it by
        # choosing a mainline branch
        ff = "false";
      };
      pull = {
        # Only enable fast-forward pulls by default, and force choosing between
        # rebasing and merging if there are conflicts, to ensure you can choose
        # the best strategy to get the best history possible
        ff = "only";
        # TODO: Remove this? ff should cover it
        rebase = "false";
      };
    };

    includes = [
      {
        condition = "gitdir:~/work/";
        contents = secrets.gitWorkConfig;
      }
    ];

    delta = {
      enable = true;
      options = {
        line-numbers = true;
        side-by-side = true; # FUTURE: Wait for (https://github.com/dandavison/delta/issues/359)
      };
    };

    aliases = {
      co = "checkout";
      ss = "status";
      cm = "commit -m";
    };
  };

}
