{ config, pkgs, ... }:
let
  # Shell functions (not scripts) so the git-wt shell hook can still cd into the worktree.
  # Same-repo PRs only; fork branches are not fetchable by name.
  gitWtFns = ''
    git-wt-pr() {
      local branch
      branch=$(gh pr list --json number,title,headRefName \
        --jq '.[] | "\(.number)\t\(.title)\t\(.headRefName)"' \
        | fzf --delimiter '\t' --with-nth 1,2 | cut -f3)
      [ -n "$branch" ] || return 1
      git fetch origin "$branch" && git wt "$branch"
    }

    # Pick an issue, reuse its linked branch or create one via `gh issue develop`.
    git-wt-issue() {
      local issue branch
      issue=$(gh issue list --json number,title \
        --jq '.[] | "\(.number)\t\(.title)"' | fzf | cut -f1)
      [ -n "$issue" ] || return 1
      branch=$(gh issue develop --list "$issue" | head -1 | cut -f1)
      [ -n "$branch" ] || branch=$(gh issue develop "$issue" | sed 's|.*/tree/||')
      [ -n "$branch" ] || return 1
      git fetch origin "$branch" && git wt "$branch"
    }
  '';
in
{
  home.packages = with pkgs; [
    git-wt
  ];

  sops.secrets.gitWorkConfig = { };

  programs.git = {
    enable = true;
    signing.key = "7E66BB1D1107BA57";
    signing.format = "openpgp";

    ignores = [
      "*~"
      "*.swp" # vim swap files
      "texfrag" # trash generated by texfrag in emacs
      "\\#*\\#" # emacs swap files
      "/result/" # nix outputs
      "/result-data/" # something related to nix output
      ".idea" # Jetbrains IDEA configuration
      "build" # gradle output
      ".gradle" # some gradle specifics I dunno
      "hs_err_pid*.log" # some Java crash logs
      "replay_pid*.log" # other random Java crash logs I guess
    ];

    settings = {
      user = {
        name = "Haf";
        email = "haf@protonmail.ch";
      };
      alias = {
        co = "checkout";
        ss = "status";
        cm = "commit -m";
      };
      credential.helper = "cache --timeout=3600";
      init.defaultBranch = "main";
      merge = {
        # Always creates a merge commit, even if a merge can be fast-forwarded.
        # If the commits are fast-forwarded, these might be very bulk in the history
        # of the base branch and make it difficult to use debugging tools like bisect,
        # or force you to revert them all if you wan't to undo the merge.

        # On the other hand, if you have a merge commit, you can just revert it by
        # choosing a mainline branch
        ff = "false";
      };
      push = {
        # Automatically set up the upstream remote on first push, so
        # `git push` works on new branches without `--set-upstream`.
        autoSetupRemote = true;
      };
      pull = {
        # Only enable fast-forward pulls by default, and force choosing between
        # rebasing and merging if there are conflicts, to ensure you can choose
        # the best strategy to get the best history possible
        ff = "only";
        # TODO: Remove this? ff should cover it
        rebase = "false";
      };
      # re-use older conflict resolutions
      # totally necessary when working on long-lived branches or
      # you'll go crazy
      rerere.enabled = true;
      # git-wt: copy .gitignore'd files (e.g. .env) into new worktrees
      wt.copyignored = true;
      # git-wt: trust .envrc in new worktrees so direnv loads without a prompt
      wt.hook = "! test -f .envrc || direnv allow";
    };

    includes = [
      {
        condition = "gitdir:~/work/";
        path = config.sops.secrets.gitWorkConfig.path;
      }
    ];

    iniContent = {
      blame.ignoreRevsFile = ".git-blame-ignore-revs";
    };
  };

  programs.delta = {
    enable = true;
    enableGitIntegration = true;
    options = {
      line-numbers = true;
      side-by-side = true; # FUTURE: Wait for (https://github.com/dandavison/delta/issues/359)
    };
  };

  # git-wt shell integration: enables `git wt` to cd into worktrees
  programs.bash.initExtra = ''
    eval "$(git-wt --init bash)"
    ${gitWtFns}
  '';
  programs.zsh.initContent = ''
    eval "$(git-wt --init zsh)"
    ${gitWtFns}
  '';

}
