{ pkgs, secrets, ... }:
{
  programs.git = {
    enable = true;
    userName = "Haf";
    userEmail = "haf@protonmail.ch";
    ignores = [ 
      "*~"
      "*.swp" # vim swap files 
      "texfrag" # trash generated by texfrag in emacs
      "\\#*\\#" # emacs swap files
      "/result/" # nix outputs
      "/result-data/" # something related to nix output
      ".idea" # Jetbrains IDEA configuration
      "build" # gradle output
      ".gradle" # some gradle specifics I dunno
      "hs_err_pid*.log" # some Java crash logs
      "replay_pid*.log" # other random Java crash logs I guess
    ];
    extraConfig = {
      credential.helper = "cache --timeout=3600";
      init.defaultBranch = "master";
      pull.rebase = "false";
    };

    includes = [
      {
        condition = "gitdir:~/work/";
        contents = secrets.gitWorkConfig;
      }
    ];

    delta = {
      enable = true;
      options = {
        line-numbers = true;
        side-by-side = true; # FUTURE: Wait for (https://github.com/dandavison/delta/issues/359)
      };
    };

    aliases = {
      co = "checkout";
      ss = "status";
      cm = "commit -m";
      #acmp = ''!f() { git add . && git commit -m "$1" && git push; }; f'';
    };
  };

}
